const fs = require('fs');

const updateKeys = {
  en: {
    "pricing_title_part1": "SIMPLE",
    "pricing_title_part2": "PRICING.",
    "pricing_desc": "Transparent pricing for both homeowners and artisans. No hidden fees, no surprises.",
    "pricing_homeowners_title": "For Homeowners",
    "pricing_homeowners_desc": "Find and book the best artisans for your home projects.",
    "pricing_free": "Free",
    "pricing_per_booking": "per booking",
    "pricing_ho_feature_1": "Access to 2,500+ verified artisans",
    "pricing_ho_feature_2": "Secure escrow payments",
    "pricing_ho_feature_3": "24/7 customer support",
    "pricing_ho_feature_4": "Detailed artisan profiles & reviews",
    "pricing_ho_feature_5": "Instant booking & scheduling",
    "pricing_ho_feature_6": "Materials marketplace access",
    "pricing_ho_btn": "Start Finding Pros",
    "pricing_artisans_title": "For Artisans",
    "pricing_artisans_desc": "Grow your business and reach more clients in your city.",
    "pricing_commission": "commission per job",
    "pricing_ar_feature_1": "Professional business profile",
    "pricing_ar_feature_2": "Unlimited booking requests",
    "pricing_ar_feature_3": "Integrated chat & scheduling",
    "pricing_ar_feature_4": "Verified identity badge",
    "pricing_ar_feature_5": "Automated invoicing & receipts",
    "pricing_ar_feature_6": "Priority support & mediation",
    "pricing_ar_btn": "Join as Artisan",
    "pricing_trust_1_title": "No Hidden Fees",
    "pricing_trust_1_desc": "What you see is what you pay. No subscription fees or surprise charges.",
    "pricing_trust_2_title": "Secure Payments",
    "pricing_trust_2_desc": "We use industry-standard encryption to keep your financial data safe.",
    "pricing_trust_3_title": "Money-Back Guarantee",
    "pricing_trust_3_desc": "If you're not satisfied with the service, we offer mediation and refunds."
  },
  ar: {
    "pricing_title_part1": "أسعار",
    "pricing_title_part2": "بسيطة ومباشرة.",
    "pricing_desc": "تسعير شفاف لكل من العملاء والحرفيين. لا رسوم خفية، لا مفاجآت.",
    "pricing_homeowners_title": "للعملاء",
    "pricing_homeowners_desc": "ابحث عن أفضل الحرفيين لمشاريع منزلك واحجزهم بسهولة.",
    "pricing_free": "مجاناً",
    "pricing_per_booking": "لكل حجز",
    "pricing_ho_feature_1": "وصول إلى أكثر من 2500 حرفي موثق",
    "pricing_ho_feature_2": "مدفوعات آمنة ومضمونة",
    "pricing_ho_feature_3": "دعم عملاء على مدار الساعة",
    "pricing_ho_feature_4": "ملفات شخصية وتقييمات مفصلة",
    "pricing_ho_feature_5": "حجز وجدولة فورية",
    "pricing_ho_feature_6": "دخول حصري لمتجر المعدات",
    "pricing_ho_btn": "ابحث عن محترف الآن",
    "pricing_artisans_title": "للحرفيين",
    "pricing_artisans_desc": "نمِّ أعمالك وصِل إلى المزيد من العملاء في مدينتك.",
    "pricing_commission": "عمولة على كل عمل",
    "pricing_ar_feature_1": "ملف تعريفي احترافي",
    "pricing_ar_feature_2": "طلبات حجز غير محدودة",
    "pricing_ar_feature_3": "محادثات وجدولة مدمجة",
    "pricing_ar_feature_4": "شارة هوية موثقة",
    "pricing_ar_feature_5": "فواتير وإيصالات آلية",
    "pricing_ar_feature_6": "دعم أولوية ووساطة",
    "pricing_ar_btn": "انضم كحرفي",
    "pricing_trust_1_title": "لا رسوم خفية",
    "pricing_trust_1_desc": "ما تراه هو ما تدفعه. لا توجد رسوم اشتراك أو مفاجآت.",
    "pricing_trust_2_title": "مدفوعات آمنة",
    "pricing_trust_2_desc": "نستخدم أحدث تقنيات التشفير للحفاظ على أمان بياناتك المالية.",
    "pricing_trust_3_title": "ضمان استرداد الأموال",
    "pricing_trust_3_desc": "إذا لم تكن راضيًا عن الخدمة، نوفر نظام وساطة واسترداد مباشر."
  },
  fr: {
    "pricing_title_part1": "TARIFICATION",
    "pricing_title_part2": "SIMPLE.",
    "pricing_desc": "Une tarification transparente pour les clients et les artisans. Aucun frais caché, aucune surprise.",
    "pricing_homeowners_title": "Pour les Clients",
    "pricing_homeowners_desc": "Trouvez et réservez les meilleurs artisans pour vos projets immobiliers.",
    "pricing_free": "Gratuit",
    "pricing_per_booking": "par réservation",
    "pricing_ho_feature_1": "Accès à plus de 2 500 artisans vérifiés",
    "pricing_ho_feature_2": "Paiements séquestres sécurisés",
    "pricing_ho_feature_3": "Support client 24/7",
    "pricing_ho_feature_4": "Profils détaillés et avis certifiés",
    "pricing_ho_feature_5": "Réservation et planification immédiates",
    "pricing_ho_feature_6": "Accès à la boutique de matériaux",
    "pricing_ho_btn": "Commencer la recherche",
    "pricing_artisans_title": "Pour les Artisans",
    "pricing_artisans_desc": "Développez votre activité et trouvez plus de clients dans votre ville.",
    "pricing_commission": "commission par mission",
    "pricing_ar_feature_1": "Profil professionnel détaillé",
    "pricing_ar_feature_2": "Demandes de réservation illimitées",
    "pricing_ar_feature_3": "Messagerie et agenda intégrés",
    "pricing_ar_feature_4": "Badge d'identité vérifiée",
    "pricing_ar_feature_5": "Facturation automatisée",
    "pricing_ar_feature_6": "Support prioritaire et médiation",
    "pricing_ar_btn": "S'inscrire comme artisan",
    "pricing_trust_1_title": "Aucun frais caché",
    "pricing_trust_1_desc": "Vous payez le prix affiché. Pas d'abonnement ni de frais surprises.",
    "pricing_trust_2_title": "Paiements Sécurisés",
    "pricing_trust_2_desc": "Vos transactions sont chiffrées avec les standards de sécurité les plus stricts.",
    "pricing_trust_3_title": "Garantie de Remboursement",
    "pricing_trust_3_desc": "En cas d'insatisfaction, notre service de médiation garantit vos remboursements."
  }
};

['en', 'fr', 'ar'].forEach(lng => {
  const path = `public/locales/${lng}.json`;
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  Object.assign(data, updateKeys[lng]);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Updated ${path}`);
});
