const fs = require('fs');

const addKeys = {
  en: {
    "discovery_label": "Discovery",
    "find_pro_title": "Find",
    "find_pro_accent": "Your Pro",
    "find_pro_desc": "Browse our network of verified professionals or let our AI match you with the perfect expert for your job.",
    "hide_filters": "Hide Filters",
    "show_filters": "Show Filters",
    "filters_title": "Filters",
    "filter_all_services": "All Services",
    "filter_city": "City",
    "filter_all_cities": "All Cities",
    "filter_distance": "Max Distance (km)",
    "filter_min_rating": "Minimum Rating",
    "filter_starting_price": "Max Price",
    "filter_min": "Min",
    "filter_max": "Max",
    "filter_experience": "Experience",
    "years": "Years",
    "filter_availability_trust": "Availability & Trust",
    "available_today": "Available Today",
    "available_week": "Available this week",
    "online_now": "Online Now",
    "verified_artisan": "Verified Background",
    "search_placeholder_artisans": "Search by name, expertise, or keyword...",
    "your_bookings_title": "Your",
    "your_bookings_accent": "Activity",
    "your_bookings_desc": "Manage your bookings, track arrivals, and request modifications.",
    "no_bookings_title": "No Bookings Yet",
    "no_bookings_desc": "You don't have any active or past bookings.",
    "nav_find_pro": "Find a Pro",
    "status_pending": "Pending",
    "status_proposal_submitted": "Proposal Received",
    "status_proposal_approved": "Proposal Approved",
    "status_en_route": "En Route",
    "status_ongoing": "Working",
    "status_in_progress": "In Progress",
    "status_finished": "Finished",
    "status_cancelled": "Cancelled",
    "status_completed": "Completed",
    "status_paid": "Paid",
    "artisan_at_location": "Artisan Arrived",
    "artisan_en_route": "Artisan is En Route",
    "service_time": "Time Elapsed",
    "total_service_time": "Total Time",
    "with_artisan": "With",
    "proposals_received": "Proposals Received",
    "accept_bid": "Accept Bid",
    "track_artisan": "Live Tracking",
    "pay_now": "Pay Now",
    "cancel": "Cancel",
    "invoice_pdf": "View Invoice",
    "rate_review": "Rate & Review",
    "details": "Details",
    "status": "Status"
  },
  fr: {
    "discovery_label": "Découverte",
    "find_pro_title": "Trouvez",
    "find_pro_accent": "Votre Pro",
    "find_pro_desc": "Parcourez notre réseau de professionnels vérifiés ou laissez notre IA trouver l'expert parfait.",
    "hide_filters": "Masquer les filtres",
    "show_filters": "Afficher les filtres",
    "filters_title": "Filtres",
    "filter_all_services": "Tous les services",
    "filter_city": "Ville",
    "filter_all_cities": "Toutes les villes",
    "filter_distance": "Distance max (km)",
    "filter_min_rating": "Note minimale",
    "filter_starting_price": "Prix max",
    "filter_min": "Min",
    "filter_max": "Max",
    "filter_experience": "Expérience",
    "years": "Ans",
    "filter_availability_trust": "Disponibilité et Confiance",
    "available_today": "Disponible aujourd'hui",
    "available_week": "Disponible cette semaine",
    "online_now": "En ligne",
    "verified_artisan": "Profil vérifié",
    "search_placeholder_artisans": "Rechercher par nom, spécialité, mot-clé...",
    "your_bookings_title": "Vos",
    "your_bookings_accent": "Activités",
    "your_bookings_desc": "Gérez vos réservations, suivez les arrivées, et communiquez avec vos pros.",
    "no_bookings_title": "Aucune réservation active",
    "no_bookings_desc": "Réservez un pro certifié dès aujourd'hui.",
    "nav_find_pro": "Trouver un pro",
    "status_pending": "En attente",
    "status_proposal_submitted": "Offre reçue",
    "status_proposal_approved": "Offre acceptée",
    "status_en_route": "En route",
    "status_ongoing": "En cours",
    "status_in_progress": "En progrès",
    "status_finished": "Terminé",
    "status_cancelled": "Annulé",
    "status_completed": "Complété",
    "status_paid": "Payé",
    "artisan_at_location": "En train de travailler",
    "artisan_en_route": "Artisan en route",
    "service_time": "Temps écoulé",
    "total_service_time": "Temps total",
    "with_artisan": "Avec",
    "proposals_received": "Offres reçues",
    "accept_bid": "Accepter l'offre",
    "track_artisan": "Suivi en direct",
    "pay_now": "Payer maintenant",
    "cancel": "Annuler",
    "invoice_pdf": "Voir Facture",
    "rate_review": "Évaluer",
    "details": "Détails",
    "status": "Statut"
  },
  ar: {
    "discovery_label": "استكشاف",
    "find_pro_title": "ابحث عن",
    "find_pro_accent": "المحترف المناسب",
    "find_pro_desc": "تصفح شبكة الفنيين المعتمدين أو دع الذكاء الاصطناعي يطابقك مع الخبير المثالي لطلبك.",
    "hide_filters": "إخفاء الفلاتر",
    "show_filters": "إظهار الفلاتر",
    "filters_title": "تصفية البحث",
    "filter_all_services": "جميع الخدمات",
    "filter_city": "المدينة",
    "filter_all_cities": "كل المدن",
    "filter_distance": "المسافة القصوى (كم)",
    "filter_min_rating": "الحد الأدنى للتقييم",
    "filter_starting_price": "السعر الأقصى",
    "filter_min": "أدنى",
    "filter_max": "أقصى",
    "filter_experience": "الخبرة",
    "years": "سنوات",
    "filter_availability_trust": "التوفر والموثوقية",
    "available_today": "متاح اليوم",
    "available_week": "متاح هذا الأسبوع",
    "online_now": "متصل الآن",
    "verified_artisan": "حساب موثق",
    "search_placeholder_artisans": "ابحث بالاسم، الخبرة، أو الكلمة المفتاحية...",
    "your_bookings_title": "سجل",
    "your_bookings_accent": "طلباتك",
    "your_bookings_desc": "أدر حجوزاتك، وتتبع مواعيد الوصول خطوة بخطوة.",
    "no_bookings_title": "لا يوجد حجوزات",
    "no_bookings_desc": "اطلب فني متخصص الآن لحل مشاكلك المهنية بأقل تكلفة وأفضل جودة",
    "nav_find_pro": "اطلب فني",
    "status_pending": "قيد الانتظار",
    "status_proposal_submitted": "تم تلقي عرض",
    "status_proposal_approved": "تم قبول العرض",
    "status_en_route": "في الطريق",
    "status_ongoing": "قيد العمل",
    "status_in_progress": "في تقدم",
    "status_finished": "انتهى العمل",
    "status_cancelled": "أُلغيت",
    "status_completed": "مكتمل",
    "status_paid": "مدفوع",
    "artisan_at_location": "الفني في الموقع",
    "artisan_en_route": "الفني في الطريق",
    "service_time": "الوقت المنقضي",
    "total_service_time": "الوقت الإجمالي",
    "with_artisan": "مع",
    "proposals_received": "عروض تم تلقيها",
    "accept_bid": "قبول العرض",
    "track_artisan": "التتبع المباشر",
    "pay_now": "ادفع الآن",
    "cancel": "إلغاء",
    "invoice_pdf": "عرض الفاتورة",
    "rate_review": "قيم الفني",
    "details": "التفاصيل",
    "status": "الحالة"
  }
};

['en', 'fr', 'ar'].forEach(lng => {
  const path = `public/locales/${lng}.json`;
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  Object.assign(data, addKeys[lng]);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Updated ${path}`);
});
