const fs = require('fs');

const updateKeys = {
  en: {
    "become_ar_badge": "Grow Your Business",
    "become_ar_title_1": "BECOME A",
    "become_ar_title_2": "PRO.",
    "become_ar_desc": "Join Morocco's largest network of verified professionals. Get more clients, manage your bookings, and build your reputation.",
    "become_ar_btn_apply": "Apply Now",
    "become_ar_btn_how": "How it Works",
    "become_ar_stat_earnings_label": "Earnings",
    "become_ar_stat_earnings_val": "Earn up to 15,000 MAD / month",
    "become_ar_ben_1_title": "More Clients",
    "become_ar_ben_1_desc": "Get access to thousands of homeowners looking for your specific skills.",
    "become_ar_ben_2_title": "Flexible Schedule",
    "become_ar_ben_2_desc": "Work when you want, where you want. You are your own boss.",
    "become_ar_ben_3_title": "Secure Payments",
    "become_ar_ben_3_desc": "Guaranteed payments for your hard work through our platform.",
    "become_ar_req_title": "Requirements.",
    "become_ar_req_subtitle": "What you need to join",
    "become_ar_req_1": "Professional ID / Cin",
    "become_ar_req_2": "Proof of Experience / Certification",
    "become_ar_req_3": "Clean Background Check",
    "become_ar_req_4": "Smartphone with Internet",
    "become_ar_process_title": "The Process.",
    "become_ar_process_subtitle": "How to get started",
    "become_ar_process_1_title": "Apply Online",
    "become_ar_process_1_desc": "Fill out our simple application form with your details and expertise.",
    "become_ar_process_2_title": "Verification",
    "become_ar_process_2_desc": "We review your documents and conduct a background check.",
    "become_ar_process_3_title": "Start Earning",
    "become_ar_process_3_desc": "Once approved, your profile goes live and you can start accepting jobs.",
    "become_ar_cta_title": "Ready to get started?",
    "become_ar_cta_desc": "Join thousands of successful artisans today.",
    "become_ar_cta_btn": "Start Your Application"
  },
  ar: {
    "become_ar_badge": "نمِّ أعمالك",
    "become_ar_title_1": "كن",
    "become_ar_title_2": "محترفاً.",
    "become_ar_desc": "انضم إلى أكبر شبكة للمحترفين الموثقين في المغرب. احصل على المزيد من العملاء، أدر حجوزاتك، وابنِ سمعتك المهنية.",
    "become_ar_btn_apply": "قدم طلبك الآن",
    "become_ar_btn_how": "كيف يعمل التطبيق",
    "become_ar_stat_earnings_label": "الأرباح",
    "become_ar_stat_earnings_val": "اكسب حتى 15,000 درهم شهرياً",
    "become_ar_ben_1_title": "المزيد من العملاء",
    "become_ar_ben_1_desc": "تواصل مع آلاف العملاء الذين يبحثون عن مهاراتك المحددة.",
    "become_ar_ben_2_title": "جدول مرن",
    "become_ar_ben_2_desc": "اعمل متى شئت، وأينما شئت. أنت مدير نفسك.",
    "become_ar_ben_3_title": "مدفوعات آمنة",
    "become_ar_ben_3_desc": "دفعات مضمونة لعملك الشاق عبر منصتنا.",
    "become_ar_req_title": "الشروط.",
    "become_ar_req_subtitle": "ما تحتاجه للانضمام",
    "become_ar_req_1": "بطاقة هوية مهنية / وطنية",
    "become_ar_req_2": "إثبات الخبرة أو شهادة تكوين",
    "become_ar_req_3": "سجل عدلي خالٍ من السوابق",
    "become_ar_req_4": "هاتف ذكي مع اتصال بالإنترنت",
    "become_ar_process_title": "خطوات الانضمام.",
    "become_ar_process_subtitle": "كيف تبدأ العمل معنا",
    "become_ar_process_1_title": "قدم طلبك عبر الإنترنت",
    "become_ar_process_1_desc": "املأ استمارة الطلب البسيطة بتفاصيلك المهنية.",
    "become_ar_process_2_title": "التحقق من الهوية",
    "become_ar_process_2_desc": "نقوم بمراجعة مستنداتك وإجراء فحص الخلفية.",
    "become_ar_process_3_title": "ابدأ في كسب المال",
    "become_ar_process_3_desc": "بمجرد الموافقة، يُنشر ملفك ويمكنك البدء في قبول الطلبات.",
    "become_ar_cta_title": "هل أنت مستعد للبدء؟",
    "become_ar_cta_desc": "انضم إلى آلاف الحرفيين الناجحين اليوم.",
    "become_ar_cta_btn": "ابدأ طلبك الآن"
  },
  fr: {
    "become_ar_badge": "Développez votre activité",
    "become_ar_title_1": "DEVENEZ UN",
    "become_ar_title_2": "PRO.",
    "become_ar_desc": "Rejoignez le plus grand réseau de professionnels vérifiés au Maroc. Obtenez plus de clients, gérez vos réservations et construisez votre réputation.",
    "become_ar_btn_apply": "Postuler",
    "become_ar_btn_how": "Comment ça marche",
    "become_ar_stat_earnings_label": "Revenus",
    "become_ar_stat_earnings_val": "Gagnez jusqu'à 15 000 MAD / mois",
    "become_ar_ben_1_title": "Plus de clients",
    "become_ar_ben_1_desc": "Accédez à des milliers de clients recherchant vos compétences spécifiques.",
    "become_ar_ben_2_title": "Horaires flexibles",
    "become_ar_ben_2_desc": "Travaillez quand et où vous voulez. Soyez votre propre patron.",
    "become_ar_ben_3_title": "Paiements Sécurisés",
    "become_ar_ben_3_desc": "Paiements garantis pour votre travail via notre plateforme.",
    "become_ar_req_title": "Critères.",
    "become_ar_req_subtitle": "Ce qu'il vous faut pour adhérer",
    "become_ar_req_1": "Carte Nationale d'Identité",
    "become_ar_req_2": "Preuve d'expérience / Diplôme",
    "become_ar_req_3": "Casier judiciaire vierge",
    "become_ar_req_4": "Smartphone avec Internet",
    "become_ar_process_title": "Le Processus.",
    "become_ar_process_subtitle": "Comment commencer",
    "become_ar_process_1_title": "Postuler en Ligne",
    "become_ar_process_1_desc": "Remplissez notre formulaire simple avec vos détails.",
    "become_ar_process_2_title": "Vérification",
    "become_ar_process_2_desc": "Nous examinons vos documents et votre profil.",
    "become_ar_process_3_title": "Commencer",
    "become_ar_process_3_desc": "Une fois approuvé, commencez à accepter des missions.",
    "become_ar_cta_title": "Prêt à commencer ?",
    "become_ar_cta_desc": "Rejoignez des milliers d'artisans prospères aujourd'hui.",
    "become_ar_cta_btn": "Démarrer"
  }
};

['en', 'fr', 'ar'].forEach(lng => {
  const path = `public/locales/${lng}.json`;
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  Object.assign(data, updateKeys[lng]);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Updated ${path}`);
});
